// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0HXhKFCZ7RlshZ3Z9c2v6nB7IaNtKlA',
    appId: '1:242189023598:web:451183f8929c618915297f',
    messagingSenderId: '242189023598',
    projectId: 'hane-hackathon',
    authDomain: 'hane-hackathon.firebaseapp.com',
    databaseURL: 'https://hane-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'hane-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5n7YZOTuYb6j0ngrKvDvRX90QcSVQIR4',
    appId: '1:242189023598:android:940855d8cfebd52715297f',
    messagingSenderId: '242189023598',
    projectId: 'hane-hackathon',
    databaseURL: 'https://hane-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'hane-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBf-zb6sC6QZ4shCsYO7gBYujmVipVhB4',
    appId: '1:242189023598:ios:e1a17f50a37eba5d15297f',
    messagingSenderId: '242189023598',
    projectId: 'hane-hackathon',
    databaseURL: 'https://hane-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'hane-hackathon.firebasestorage.app',
    iosBundleId: 'com.teksas.hane',
  );
}
